export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const ADD_ARTICAL = "ADD_ARTICAL"
export const UPDATE_USERINFO = "UPDATE_USERINFO"
export const ADD_OWN_ARTICAL = "ADD_OWN_ARTICAL"
export const DELETE_OWN_ARTICAL = "DELETE_OWN_ARTICAL"
export const ADD_OWN_COLLECT = "ADD_OWN_COLLECT"
export const DELETE_OWN_COLLECT = "DELETE_OWN_COLLECT"
export const ADD_OWN_LIKE = "ADD_OWN_LIKE"
export const DELETE_OWN_LIKE = "DELETE_OWN_LIKE"
export const ADD_OWN_MESSAGE = "ADD_OWN_MESSAGE"
export const ADD_FOLLOW = "ADD_FOLLOW"
export const DELETE_FOLLOW = "DELETE_FOLLOW"
export const DELETE_MESSAGE = "DELETE_MESSAGE"
export const ADD_FOLLOW_COUNT = "ADD_FOLLOW_COUNT"
export const DELETE_FOLLOW_COUNT = "DELETE_FOLLOW_COUNT"
export const ADD_DYNAMIC_COUNT = "ADD_DYNAMIC_COUNT"
export const DELETE_DYNAMIC_COUNT = "DELETE_DYNAMIC_COUNT"












